// import ReactLenis from "lenis/react";
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export const viewport: Viewport = {
  themeColor: "#181b1e"
  // colorScheme: "dark"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <ReactLenis root> */}

        {children}

        {/* </ReactLenis> */}
        <NextTopLoader
          showSpinner={false}
          color="var(--primary)"
          zIndex={999}
          height={3}
        />
      </body>
    </html>
  );
}
